name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["10.x"]

    steps:
      - uses: actions/checkout@v1
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up MariaDB 10
        uses: ChasNelson1990/mariadb-action@master
        with:
          mariadb_version: 10.4.10
          primary_database: database
          secondary_database: test_database
          root_password: testingpasswordREMOVE
      - name: npm install, build, and test
        env:
          password: testingpasswordREMOVE
        run: |
          npm install
          npm run lint
          npm test -- --password=${password}
